### ISSUE TITLE
Specifying disabled experimental rule in .editorconfig doesn't seem to do anything?

### ISSUE THREAD

**Issue by takanuva15** [JLLeitschuh/ktlint-gradle#663]
I'm working on upgrading the build script of an intellij plugin to the latest ktlint-gradle plugin version. Previously, I enabled all experimental rules but disabled the [package-naming experimental rule](https://pinterest.github.io/ktlint/rules/experimental/#package-naming). My `build.gradle.kts` looked like this:
```
ktlint {
    enableExperimentalRules.set(true)
    disabledRules.set(setOf("experimental:package-name"))
}
```
I had no issues with this config and stuff was working fine.

With the new version of the ktlint-gradle plugin though, I can't use "disabledRules" anymore. It looks like I'm supposed to specify the rules to disable in `.editorconfig` instead, but it doesn't seem to be working for me:

Here's my new `build.gradle.kts`:
```
...
    id("org.jlleitschuh.gradle.ktlint") version "11.+"
...
ktlint {
    version.set("0.48.2")
    enableExperimentalRules.set(true)
}
```

Here's my new `.editorconfig`:
```
root=true
...
[*.{kt,kts}]
ktlint_experimental_package-naming = disabled
```

Even with these 2 configured, when I run the ktlintCheck task, it fails and spews errors about incorrect package-names all over the console. I've probably spent a few hours debugging and scouring the internet to fix this seemingly simple ktlint issue, so I'm finally throwing in the towel and posting an issue here to see if I'm doing something wrong.

(For reference, here's the PR in my intellij plugin where I'm working on upgrading ktlint: https://github.com/Nordgedanken/intellij-autohotkey/pull/71 )

**Comment by wakingrufus** [comment]
Thanks for the report! I can take a look at this next week

**Comment by Daeda88** [comment]
Running into the same issue. My Android Studio is reporting "The property is not supported" for `ktlint_code_style = ktlint_official` in my `.editorconfig` so Im guessing all ktlint rules are just ignored

**Comment by wakingrufus** [comment]
I just released 11.3.2 which fixes a bug related to .editorconfig detection. I am not sure if this will address these issues, but can you please try it out and report back if your issues have resolved?

**Comment by takanuva15** [comment]
Hey I tried it today with v11.3.2 and it looks like I'm still seeing the same error about `Package name must not contain underscore`. This is my `.editorconfig`:
```
root = true
...
[*.{kt,kts}]
ktlint_experimental_package-naming = disabled
```

I made a dummy class with dummy package:
```kt
package com.autohotkey.ide.test_bad

class Test {
    init {
        print("hi")
    }
}
```

And when I run the `ktlintCheck` task, it errors out with this output:
```
> Task :ktlintMainSourceSetCheck FAILED
C:\<path>\src\main\kotlin\com\autohotkey\ide\test_bad\Test.kt:1:9 Package name must not contain underscore (cannot be auto-corrected)
7 actionable tasks: 2 executed, 5 up-to-date
```

**Comment by wakingrufus** [comment]
> @wakingrufus Hey I tried it today with v11.3.2 and it looks like I'm still seeing the same error about `Package name must not contain underscore`. This is my `.editorconfig`:
> ```
> root = true
> ...
> [*.{kt,kts}]
> ktlint_experimental_package-naming = disabled
> ```
> 
> I made a dummy class with dummy package:
> ```kt
> package com.autohotkey.ide.test_bad
> 
> class Test {
>     init {
>         print("hi")
>     }
> }
> ```
> 
> And when I run the `ktlintCheck` task, it errors out with this output:
> ```
> > Task :ktlintMainSourceSetCheck FAILED
> C:\<path>\src\main\kotlin\com\autohotkey\ide\test_bad\Test.kt:1:9 Package name must not contain underscore (cannot be auto-corrected)
> 7 actionable tasks: 2 executed, 5 up-to-date
> ```

Thanks, I'll dig into this some more.

**Comment by paul-dingemans** [comment]
The `experimental` rule set no longer exists. All experimental rules are moved to the 'standard` rule set. Rules can still be marked with an `experimental` flag which is used by property `ktlint_experimental`. In your case, you should use following:
```
root = true
...
[*.{kt,kts}]
ktlint_standard_package-naming = disabled
```

Disclaimer: I am maintainer of Ktlint but have almost to 0% knowledge of ktlint-gradle plugin ;-)
